data_path:
  x_pos: data/pi_xs.npy
  y_pos: data/pi_ys.npy
  image: data/sparse_pi_colored.jpg
  output_samples: output/output_samples_gan.npy
  output_image: output/output_image_gan.jpg
model:
  type: "gan"
  input_dim: 5
  latent_dim: 10
  hidden_dim: [64, 32]
  dg_ratio: 3
hyperparameter:
  learning_rate_g: 0.00005
  learning_rate_d: 0.0001
  learning_rate_vae: 0.001
  beta1: 0.5
  beta2: 0.999
  batch_size: 32
  split_ratio: 1
  epochs: 300
  device: "mps"
  num_samples: 5000
task:
  train: true
  sample: true
