data_path:
  x_pos: data/pi_xs.npy
  y_pos: data/pi_ys.npy
  image: data/sparse_pi_colored.jpg
  output_samples: output/output_samples_gan.npy
  output_image: output/output_image_gan.jpg
model:
  type: "gan"
  input_dim: 5
  latent_dim: 5
  hidden_dim: [32, 16]
hyperparameter:
  learning_rate_g: 0.001
  learning_rate_d: 0.001
  learning_rate_vae: 0.001
  batch_size: 64
  split_ratio: 1
  epochs: 100
  device: "mps"
  num_samples: 5000
task:
  train: true
  sample: true
